const Map<String, String> kCurrencyNames = {
  'AUD': 'Australian Dollar',
  'BGN': 'Bulgarian Lev',
  'BRL': 'Brazilian Real',
  'CAD': 'Canadian Dollar',
  'CHF': 'Swiss Franc',
  'CNY': 'Chinese Yuan',
  'CZK': 'Czech Koruna',
  'DKK': 'Danish Krone',
  'EUR': 'Euro',
  'GBP': 'British Pound',
  'HKD': 'Hong Kong Dollar',
  'HUF': 'Hungarian Forint',
  'IDR': 'Indonesian Rupiah',
  'ILS': 'Israeli Shekel',
  'INR': 'Indian Rupee',
  'ISK': 'Icelandic Krona',
  'JPY': 'Japanese Yen',
  'KRW': 'South Korean Won',
  'MXN': 'Mexican Peso',
  'MYR': 'Malaysian Ringgit',
  'NOK': 'Norwegian Krone',
  'NZD': 'New Zealand Dollar',
  'PHP': 'Philippine Peso',
  'PLN': 'Polish Zloty',
  'RON': 'Romanian Leu',
  'SEK': 'Swedish Krona',
  'SGD': 'Singapore Dollar',
  'THB': 'Thai Baht',
  'TRY': 'Turkish Lira',
  'USD': 'US Dollar',
  'ZAR': 'South African Rand',
};

const Map<String, String> kCurrencySymbols = {
  'AUD': 'A\$',
  'BGN': 'лв',
  'BRL': 'R\$',
  'CAD': 'C\$',
  'CHF': '₣',
  'CNY': '¥',
  'CZK': 'Kč',
  'DKK': 'kr',
  'EUR': '€',
  'GBP': '£',
  'HKD': 'HK\$',
  'HUF': 'Ft',
  'IDR': 'Rp',
  'ILS': '₪',
  'INR': '₹',
  'ISK': 'kr',
  'JPY': '¥',
  'KRW': '₩',
  'MXN': 'M\$',
  'MYR': 'RM',
  'NOK': 'kr',
  'NZD': 'NZ\$',
  'PHP': '₱',
  'PLN': 'zł',
  'RON': 'lei',
  'SEK': 'kr',
  'SGD': 'S\$',
  'THB': '฿',
  'TRY': '₺',
  'USD': '\$',
  'ZAR': 'R',
};
